# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0002_song_formatted_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='formatted_author',
            field=models.CharField(default='', max_length=40),
        ),
    ]
